//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36241
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saldo.Account {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileAccount", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Entidades")]
    public enum ProfileAccount : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dealer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.DealerSearchCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.ManifestSearchCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.UserSearchCriteria))]
    public partial class SearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealerSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class DealerSearchCriteria : Saldo.Account.SearchCriteria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalName {
            get {
                return this.LegalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNameField, value) != true)) {
                    this.LegalNameField = value;
                    this.RaisePropertyChanged("LegalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc {
            get {
                return this.RfcField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcField, value) != true)) {
                    this.RfcField = value;
                    this.RaisePropertyChanged("Rfc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManifestSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class ManifestSearchCriteria : Saldo.Account.SearchCriteria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdDealerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdDealer {
            get {
                return this.IdDealerField;
            }
            set {
                if ((this.IdDealerField.Equals(value) != true)) {
                    this.IdDealerField = value;
                    this.RaisePropertyChanged("IdDealer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class UserSearchCriteria : Saldo.Account.SearchCriteria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdDealerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdDealer {
            get {
                return this.IdDealerField;
            }
            set {
                if ((this.IdDealerField.Equals(value) != true)) {
                    this.IdDealerField = value;
                    this.RaisePropertyChanged("IdDealer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((this.ProfileField.Equals(value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surnames {
            get {
                return this.SurnamesField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnamesField, value) != true)) {
                    this.SurnamesField = value;
                    this.RaisePropertyChanged("Surnames");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.SearchResultDealers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.SearchResultManifest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.SearchResultUsers))]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalEntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalEntries {
            get {
                return this.TotalEntriesField;
            }
            set {
                if ((this.TotalEntriesField.Equals(value) != true)) {
                    this.TotalEntriesField = value;
                    this.RaisePropertyChanged("TotalEntries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResultDealers", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class SearchResultDealers : Saldo.Account.SearchResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Saldo.Account.ClientResult[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Saldo.Account.ClientResult[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResultManifest", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class SearchResultManifest : Saldo.Account.SearchResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Saldo.Account.Manifiesto[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Saldo.Account.Manifiesto[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResultUsers", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class SearchResultUsers : Saldo.Account.SearchResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Saldo.Account.UserResult[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Saldo.Account.UserResult[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResult", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class UserResult : Saldo.Account.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> StampsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UnlimitedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Stamps {
            get {
                return this.StampsField;
            }
            set {
                if ((this.StampsField.Equals(value) != true)) {
                    this.StampsField = value;
                    this.RaisePropertyChanged("Stamps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Unlimited {
            get {
                return this.UnlimitedField;
            }
            set {
                if ((this.UnlimitedField.Equals(value) != true)) {
                    this.UnlimitedField = value;
                    this.RaisePropertyChanged("Unlimited");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientResult", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Entities")]
    [System.SerializableAttribute()]
    public partial class ClientResult : Saldo.Account.Cliente {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> StampsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Stamps {
            get {
                return this.StampsField;
            }
            set {
                if ((this.StampsField.Equals(value) != true)) {
                    this.StampsField = value;
                    this.RaisePropertyChanged("Stamps");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Context")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.ClientResult))]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> MultiRfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Saldo.Account.Usuario[] UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<bool> MultiRfc {
            get {
                return this.MultiRfcField;
            }
            set {
                if ((this.MultiRfcField.Equals(value) != true)) {
                    this.MultiRfcField = value;
                    this.RaisePropertyChanged("MultiRfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Saldo.Account.Usuario[] Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Context")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Saldo.Account.UserResult))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaUltimoPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegisteredDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime FechaUltimoPassword {
            get {
                return this.FechaUltimoPasswordField;
            }
            set {
                if ((this.FechaUltimoPasswordField.Equals(value) != true)) {
                    this.FechaUltimoPasswordField = value;
                    this.RaisePropertyChanged("FechaUltimoPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((this.AdministradorField.Equals(value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<int> Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((this.ProfileField.Equals(value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<System.DateTime> RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manifiesto", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Context")]
    [System.SerializableAttribute()]
    public partial class Manifiesto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FirmadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> TipoFirma {
            get {
                return this.TipoFirmaField;
            }
            set {
                if ((this.TipoFirmaField.Equals(value) != true)) {
                    this.TipoFirmaField = value;
                    this.RaisePropertyChanged("TipoFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> FechaFirma {
            get {
                return this.FechaFirmaField;
            }
            set {
                if ((this.FechaFirmaField.Equals(value) != true)) {
                    this.FechaFirmaField = value;
                    this.RaisePropertyChanged("FechaFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<bool> Firmado {
            get {
                return this.FirmadoField;
            }
            set {
                if ((this.FirmadoField.Equals(value) != true)) {
                    this.FirmadoField = value;
                    this.RaisePropertyChanged("Firmado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.Guid> IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaldoCliente", Namespace="http://schemas.datacontract.org/2004/07/SuFacturacion.Account.Context")]
    [System.SerializableAttribute()]
    public partial class SaldoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdSaldoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdClienteUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SaldoTimbresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TimbresUtilizadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaExpiracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UnlimitedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdSaldoCliente {
            get {
                return this.IdSaldoClienteField;
            }
            set {
                if ((this.IdSaldoClienteField.Equals(value) != true)) {
                    this.IdSaldoClienteField = value;
                    this.RaisePropertyChanged("IdSaldoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid IdClienteUsuario {
            get {
                return this.IdClienteUsuarioField;
            }
            set {
                if ((this.IdClienteUsuarioField.Equals(value) != true)) {
                    this.IdClienteUsuarioField = value;
                    this.RaisePropertyChanged("IdClienteUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long SaldoTimbres {
            get {
                return this.SaldoTimbresField;
            }
            set {
                if ((this.SaldoTimbresField.Equals(value) != true)) {
                    this.SaldoTimbresField = value;
                    this.RaisePropertyChanged("SaldoTimbres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> TimbresUtilizados {
            get {
                return this.TimbresUtilizadosField;
            }
            set {
                if ((this.TimbresUtilizadosField.Equals(value) != true)) {
                    this.TimbresUtilizadosField = value;
                    this.RaisePropertyChanged("TimbresUtilizados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> FechaExpiracion {
            get {
                return this.FechaExpiracionField;
            }
            set {
                if ((this.FechaExpiracionField.Equals(value) != true)) {
                    this.FechaExpiracionField = value;
                    this.RaisePropertyChanged("FechaExpiracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<bool> Unlimited {
            get {
                return this.UnlimitedField;
            }
            set {
                if ((this.UnlimitedField.Equals(value) != true)) {
                    this.UnlimitedField = value;
                    this.RaisePropertyChanged("Unlimited");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Account.IwsAccount")]
    public interface IwsAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateDealer", ReplyAction="http://tempuri.org/IwsAccount/CreateDealerResponse")]
        System.Guid CreateDealer(string email, string password, string name, string surnames, string taxid, string legalName, Saldo.Account.ProfileAccount profile, long stamps, bool unlimited, bool multiRfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateDealer", ReplyAction="http://tempuri.org/IwsAccount/CreateDealerResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateDealerAsync(string email, string password, string name, string surnames, string taxid, string legalName, Saldo.Account.ProfileAccount profile, long stamps, bool unlimited, bool multiRfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateUser", ReplyAction="http://tempuri.org/IwsAccount/CreateUserResponse")]
        System.Guid CreateUser(string email, string password, string name, string surnames, Saldo.Account.ProfileAccount profile, long stamps, System.Guid idParent, bool unlimited);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateUser", ReplyAction="http://tempuri.org/IwsAccount/CreateUserResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateUserAsync(string email, string password, string name, string surnames, Saldo.Account.ProfileAccount profile, long stamps, System.Guid idParent, bool unlimited);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/SaveDealer", ReplyAction="http://tempuri.org/IwsAccount/SaveDealerResponse")]
        void SaveDealer(System.Guid idUser, System.Guid idDealer, string name, string surnames, bool active, bool unlimited, bool multiRfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/SaveDealer", ReplyAction="http://tempuri.org/IwsAccount/SaveDealerResponse")]
        System.Threading.Tasks.Task SaveDealerAsync(System.Guid idUser, System.Guid idDealer, string name, string surnames, bool active, bool unlimited, bool multiRfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/SaveUser", ReplyAction="http://tempuri.org/IwsAccount/SaveUserResponse")]
        void SaveUser(System.Guid idUser, string name, string surnames, bool active, bool unlimited);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/SaveUser", ReplyAction="http://tempuri.org/IwsAccount/SaveUserResponse")]
        System.Threading.Tasks.Task SaveUserAsync(System.Guid idUser, string name, string surnames, bool active, bool unlimited);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/ActivateUser", ReplyAction="http://tempuri.org/IwsAccount/ActivateUserResponse")]
        void ActivateUser(System.Guid idUser, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/ActivateUser", ReplyAction="http://tempuri.org/IwsAccount/ActivateUserResponse")]
        System.Threading.Tasks.Task ActivateUserAsync(System.Guid idUser, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetUsers", ReplyAction="http://tempuri.org/IwsAccount/GetUsersResponse")]
        Saldo.Account.SearchResultUsers GetUsers(Saldo.Account.UserSearchCriteria sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetUsers", ReplyAction="http://tempuri.org/IwsAccount/GetUsersResponse")]
        System.Threading.Tasks.Task<Saldo.Account.SearchResultUsers> GetUsersAsync(Saldo.Account.UserSearchCriteria sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetDealers", ReplyAction="http://tempuri.org/IwsAccount/GetDealersResponse")]
        Saldo.Account.SearchResultDealers GetDealers(Saldo.Account.DealerSearchCriteria sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetDealers", ReplyAction="http://tempuri.org/IwsAccount/GetDealersResponse")]
        System.Threading.Tasks.Task<Saldo.Account.SearchResultDealers> GetDealersAsync(Saldo.Account.DealerSearchCriteria sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetUserById", ReplyAction="http://tempuri.org/IwsAccount/GetUserByIdResponse")]
        Saldo.Account.Usuario GetUserById();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetUserById", ReplyAction="http://tempuri.org/IwsAccount/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Saldo.Account.Usuario> GetUserByIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetClientById", ReplyAction="http://tempuri.org/IwsAccount/GetClientByIdResponse")]
        Saldo.Account.Cliente GetClientById();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetClientById", ReplyAction="http://tempuri.org/IwsAccount/GetClientByIdResponse")]
        System.Threading.Tasks.Task<Saldo.Account.Cliente> GetClientByIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetSaldoClientById", ReplyAction="http://tempuri.org/IwsAccount/GetSaldoClientByIdResponse")]
        Saldo.Account.SaldoCliente GetSaldoClientById(System.Nullable<System.Guid> idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetSaldoClientById", ReplyAction="http://tempuri.org/IwsAccount/GetSaldoClientByIdResponse")]
        System.Threading.Tasks.Task<Saldo.Account.SaldoCliente> GetSaldoClientByIdAsync(System.Nullable<System.Guid> idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/AddStampsUser", ReplyAction="http://tempuri.org/IwsAccount/AddStampsUserResponse")]
        void AddStampsUser(System.Guid idDealer, System.Guid idUser, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/AddStampsUser", ReplyAction="http://tempuri.org/IwsAccount/AddStampsUserResponse")]
        System.Threading.Tasks.Task AddStampsUserAsync(System.Guid idDealer, System.Guid idUser, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveStampsUser", ReplyAction="http://tempuri.org/IwsAccount/RemoveStampsUserResponse")]
        void RemoveStampsUser(System.Guid idDealer, System.Guid idUser, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveStampsUser", ReplyAction="http://tempuri.org/IwsAccount/RemoveStampsUserResponse")]
        System.Threading.Tasks.Task RemoveStampsUserAsync(System.Guid idDealer, System.Guid idUser, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/AddStampsDealer", ReplyAction="http://tempuri.org/IwsAccount/AddStampsDealerResponse")]
        void AddStampsDealer(System.Guid idDealer, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/AddStampsDealer", ReplyAction="http://tempuri.org/IwsAccount/AddStampsDealerResponse")]
        System.Threading.Tasks.Task AddStampsDealerAsync(System.Guid idDealer, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveStampsDealer", ReplyAction="http://tempuri.org/IwsAccount/RemoveStampsDealerResponse")]
        void RemoveStampsDealer(System.Guid idDealer, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveStampsDealer", ReplyAction="http://tempuri.org/IwsAccount/RemoveStampsDealerResponse")]
        System.Threading.Tasks.Task RemoveStampsDealerAsync(System.Guid idDealer, long stamps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateManiFest", ReplyAction="http://tempuri.org/IwsAccount/CreateManiFestResponse")]
        void CreateManiFest(string Rfc, System.Guid idDealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/CreateManiFest", ReplyAction="http://tempuri.org/IwsAccount/CreateManiFestResponse")]
        System.Threading.Tasks.Task CreateManiFestAsync(string Rfc, System.Guid idDealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveManiFestDealer", ReplyAction="http://tempuri.org/IwsAccount/RemoveManiFestDealerResponse")]
        void RemoveManiFestDealer(string Rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveManiFestDealer", ReplyAction="http://tempuri.org/IwsAccount/RemoveManiFestDealerResponse")]
        System.Threading.Tasks.Task RemoveManiFestDealerAsync(string Rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveManiFestAdmin", ReplyAction="http://tempuri.org/IwsAccount/RemoveManiFestAdminResponse")]
        void RemoveManiFestAdmin(string Rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/RemoveManiFestAdmin", ReplyAction="http://tempuri.org/IwsAccount/RemoveManiFestAdminResponse")]
        System.Threading.Tasks.Task RemoveManiFestAdminAsync(string Rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/ReAsignIdCliente", ReplyAction="http://tempuri.org/IwsAccount/ReAsignIdClienteResponse")]
        void ReAsignIdCliente(string Rfc, System.Guid idDealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/ReAsignIdCliente", ReplyAction="http://tempuri.org/IwsAccount/ReAsignIdClienteResponse")]
        System.Threading.Tasks.Task ReAsignIdClienteAsync(string Rfc, System.Guid idDealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetManiFests", ReplyAction="http://tempuri.org/IwsAccount/GetManiFestsResponse")]
        Saldo.Account.SearchResultManifest GetManiFests(Saldo.Account.ManifestSearchCriteria sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsAccount/GetManiFests", ReplyAction="http://tempuri.org/IwsAccount/GetManiFestsResponse")]
        System.Threading.Tasks.Task<Saldo.Account.SearchResultManifest> GetManiFestsAsync(Saldo.Account.ManifestSearchCriteria sc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsAccountChannel : Saldo.Account.IwsAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsAccountClient : System.ServiceModel.ClientBase<Saldo.Account.IwsAccount>, Saldo.Account.IwsAccount {
        
        public IwsAccountClient() {
        }
        
        public IwsAccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsAccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsAccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CreateDealer(string email, string password, string name, string surnames, string taxid, string legalName, Saldo.Account.ProfileAccount profile, long stamps, bool unlimited, bool multiRfc) {
            return base.Channel.CreateDealer(email, password, name, surnames, taxid, legalName, profile, stamps, unlimited, multiRfc);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateDealerAsync(string email, string password, string name, string surnames, string taxid, string legalName, Saldo.Account.ProfileAccount profile, long stamps, bool unlimited, bool multiRfc) {
            return base.Channel.CreateDealerAsync(email, password, name, surnames, taxid, legalName, profile, stamps, unlimited, multiRfc);
        }
        
        public System.Guid CreateUser(string email, string password, string name, string surnames, Saldo.Account.ProfileAccount profile, long stamps, System.Guid idParent, bool unlimited) {
            return base.Channel.CreateUser(email, password, name, surnames, profile, stamps, idParent, unlimited);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateUserAsync(string email, string password, string name, string surnames, Saldo.Account.ProfileAccount profile, long stamps, System.Guid idParent, bool unlimited) {
            return base.Channel.CreateUserAsync(email, password, name, surnames, profile, stamps, idParent, unlimited);
        }
        
        public void SaveDealer(System.Guid idUser, System.Guid idDealer, string name, string surnames, bool active, bool unlimited, bool multiRfc) {
            base.Channel.SaveDealer(idUser, idDealer, name, surnames, active, unlimited, multiRfc);
        }
        
        public System.Threading.Tasks.Task SaveDealerAsync(System.Guid idUser, System.Guid idDealer, string name, string surnames, bool active, bool unlimited, bool multiRfc) {
            return base.Channel.SaveDealerAsync(idUser, idDealer, name, surnames, active, unlimited, multiRfc);
        }
        
        public void SaveUser(System.Guid idUser, string name, string surnames, bool active, bool unlimited) {
            base.Channel.SaveUser(idUser, name, surnames, active, unlimited);
        }
        
        public System.Threading.Tasks.Task SaveUserAsync(System.Guid idUser, string name, string surnames, bool active, bool unlimited) {
            return base.Channel.SaveUserAsync(idUser, name, surnames, active, unlimited);
        }
        
        public void ActivateUser(System.Guid idUser, bool active) {
            base.Channel.ActivateUser(idUser, active);
        }
        
        public System.Threading.Tasks.Task ActivateUserAsync(System.Guid idUser, bool active) {
            return base.Channel.ActivateUserAsync(idUser, active);
        }
        
        public Saldo.Account.SearchResultUsers GetUsers(Saldo.Account.UserSearchCriteria sc) {
            return base.Channel.GetUsers(sc);
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.SearchResultUsers> GetUsersAsync(Saldo.Account.UserSearchCriteria sc) {
            return base.Channel.GetUsersAsync(sc);
        }
        
        public Saldo.Account.SearchResultDealers GetDealers(Saldo.Account.DealerSearchCriteria sc) {
            return base.Channel.GetDealers(sc);
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.SearchResultDealers> GetDealersAsync(Saldo.Account.DealerSearchCriteria sc) {
            return base.Channel.GetDealersAsync(sc);
        }
        
        public Saldo.Account.Usuario GetUserById() {
            return base.Channel.GetUserById();
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.Usuario> GetUserByIdAsync() {
            return base.Channel.GetUserByIdAsync();
        }
        
        public Saldo.Account.Cliente GetClientById() {
            return base.Channel.GetClientById();
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.Cliente> GetClientByIdAsync() {
            return base.Channel.GetClientByIdAsync();
        }
        
        public Saldo.Account.SaldoCliente GetSaldoClientById(System.Nullable<System.Guid> idUser) {
            return base.Channel.GetSaldoClientById(idUser);
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.SaldoCliente> GetSaldoClientByIdAsync(System.Nullable<System.Guid> idUser) {
            return base.Channel.GetSaldoClientByIdAsync(idUser);
        }
        
        public void AddStampsUser(System.Guid idDealer, System.Guid idUser, long stamps) {
            base.Channel.AddStampsUser(idDealer, idUser, stamps);
        }
        
        public System.Threading.Tasks.Task AddStampsUserAsync(System.Guid idDealer, System.Guid idUser, long stamps) {
            return base.Channel.AddStampsUserAsync(idDealer, idUser, stamps);
        }
        
        public void RemoveStampsUser(System.Guid idDealer, System.Guid idUser, long stamps) {
            base.Channel.RemoveStampsUser(idDealer, idUser, stamps);
        }
        
        public System.Threading.Tasks.Task RemoveStampsUserAsync(System.Guid idDealer, System.Guid idUser, long stamps) {
            return base.Channel.RemoveStampsUserAsync(idDealer, idUser, stamps);
        }
        
        public void AddStampsDealer(System.Guid idDealer, long stamps) {
            base.Channel.AddStampsDealer(idDealer, stamps);
        }
        
        public System.Threading.Tasks.Task AddStampsDealerAsync(System.Guid idDealer, long stamps) {
            return base.Channel.AddStampsDealerAsync(idDealer, stamps);
        }
        
        public void RemoveStampsDealer(System.Guid idDealer, long stamps) {
            base.Channel.RemoveStampsDealer(idDealer, stamps);
        }
        
        public System.Threading.Tasks.Task RemoveStampsDealerAsync(System.Guid idDealer, long stamps) {
            return base.Channel.RemoveStampsDealerAsync(idDealer, stamps);
        }
        
        public void CreateManiFest(string Rfc, System.Guid idDealer) {
            base.Channel.CreateManiFest(Rfc, idDealer);
        }
        
        public System.Threading.Tasks.Task CreateManiFestAsync(string Rfc, System.Guid idDealer) {
            return base.Channel.CreateManiFestAsync(Rfc, idDealer);
        }
        
        public void RemoveManiFestDealer(string Rfc) {
            base.Channel.RemoveManiFestDealer(Rfc);
        }
        
        public System.Threading.Tasks.Task RemoveManiFestDealerAsync(string Rfc) {
            return base.Channel.RemoveManiFestDealerAsync(Rfc);
        }
        
        public void RemoveManiFestAdmin(string Rfc) {
            base.Channel.RemoveManiFestAdmin(Rfc);
        }
        
        public System.Threading.Tasks.Task RemoveManiFestAdminAsync(string Rfc) {
            return base.Channel.RemoveManiFestAdminAsync(Rfc);
        }
        
        public void ReAsignIdCliente(string Rfc, System.Guid idDealer) {
            base.Channel.ReAsignIdCliente(Rfc, idDealer);
        }
        
        public System.Threading.Tasks.Task ReAsignIdClienteAsync(string Rfc, System.Guid idDealer) {
            return base.Channel.ReAsignIdClienteAsync(Rfc, idDealer);
        }
        
        public Saldo.Account.SearchResultManifest GetManiFests(Saldo.Account.ManifestSearchCriteria sc) {
            return base.Channel.GetManiFests(sc);
        }
        
        public System.Threading.Tasks.Task<Saldo.Account.SearchResultManifest> GetManiFestsAsync(Saldo.Account.ManifestSearchCriteria sc) {
            return base.Channel.GetManiFestsAsync(sc);
        }
    }
}
