//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36241
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timbrado.Autenticacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sufacturacion.com/", ConfigurationName="Autenticacion.wsAutenticacionSoap")]
    public interface wsAutenticacionSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://sufacturacion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/AutenticarBasico", ReplyAction="*")]
        Timbrado.Autenticacion.AutenticarBasicoResponse AutenticarBasico(Timbrado.Autenticacion.AutenticarBasicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/AutenticarBasico", ReplyAction="*")]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoResponse> AutenticarBasicoAsync(Timbrado.Autenticacion.AutenticarBasicoRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://sufacturacion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/AutenticarBasicoBatchProcess", ReplyAction="*")]
        Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse AutenticarBasicoBatchProcess(Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/AutenticarBasicoBatchProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse> AutenticarBasicoBatchProcessAsync(Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://sufacturacion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/TokenCambioContraseña", ReplyAction="*")]
        Timbrado.Autenticacion.TokenCambioContraseñaResponse TokenCambioContraseña(Timbrado.Autenticacion.TokenCambioContraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/TokenCambioContraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.TokenCambioContraseñaResponse> TokenCambioContraseñaAsync(Timbrado.Autenticacion.TokenCambioContraseñaRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://sufacturacion.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/CambioContraseña", ReplyAction="*")]
        Timbrado.Autenticacion.CambioContraseñaResponse CambioContraseña(Timbrado.Autenticacion.CambioContraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sufacturacion.com/CambioContraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.CambioContraseñaResponse> CambioContraseñaAsync(Timbrado.Autenticacion.CambioContraseñaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarBasicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarBasico", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.AutenticarBasicoRequestBody Body;
        
        public AutenticarBasicoRequest() {
        }
        
        public AutenticarBasicoRequest(Timbrado.Autenticacion.AutenticarBasicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class AutenticarBasicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticarBasicoRequestBody() {
        }
        
        public AutenticarBasicoRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarBasicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarBasicoResponse", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.AutenticarBasicoResponseBody Body;
        
        public AutenticarBasicoResponse() {
        }
        
        public AutenticarBasicoResponse(Timbrado.Autenticacion.AutenticarBasicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class AutenticarBasicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutenticarBasicoResult;
        
        public AutenticarBasicoResponseBody() {
        }
        
        public AutenticarBasicoResponseBody(string AutenticarBasicoResult) {
            this.AutenticarBasicoResult = AutenticarBasicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarBasicoBatchProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarBasicoBatchProcess", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequestBody Body;
        
        public AutenticarBasicoBatchProcessRequest() {
        }
        
        public AutenticarBasicoBatchProcessRequest(Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class AutenticarBasicoBatchProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticarBasicoBatchProcessRequestBody() {
        }
        
        public AutenticarBasicoBatchProcessRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarBasicoBatchProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarBasicoBatchProcessResponse", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponseBody Body;
        
        public AutenticarBasicoBatchProcessResponse() {
        }
        
        public AutenticarBasicoBatchProcessResponse(Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class AutenticarBasicoBatchProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutenticarBasicoBatchProcessResult;
        
        public AutenticarBasicoBatchProcessResponseBody() {
        }
        
        public AutenticarBasicoBatchProcessResponseBody(string AutenticarBasicoBatchProcessResult) {
            this.AutenticarBasicoBatchProcessResult = AutenticarBasicoBatchProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenCambioContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenCambioContraseña", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.TokenCambioContraseñaRequestBody Body;
        
        public TokenCambioContraseñaRequest() {
        }
        
        public TokenCambioContraseñaRequest(Timbrado.Autenticacion.TokenCambioContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class TokenCambioContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public TokenCambioContraseñaRequestBody() {
        }
        
        public TokenCambioContraseñaRequestBody(string apiKey, string email) {
            this.apiKey = apiKey;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenCambioContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenCambioContraseñaResponse", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.TokenCambioContraseñaResponseBody Body;
        
        public TokenCambioContraseñaResponse() {
        }
        
        public TokenCambioContraseñaResponse(Timbrado.Autenticacion.TokenCambioContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class TokenCambioContraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenCambioContraseñaResult;
        
        public TokenCambioContraseñaResponseBody() {
        }
        
        public TokenCambioContraseñaResponseBody(string TokenCambioContraseñaResult) {
            this.TokenCambioContraseñaResult = TokenCambioContraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambioContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambioContraseña", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.CambioContraseñaRequestBody Body;
        
        public CambioContraseñaRequest() {
        }
        
        public CambioContraseñaRequest(Timbrado.Autenticacion.CambioContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sufacturacion.com/")]
    public partial class CambioContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public CambioContraseñaRequestBody() {
        }
        
        public CambioContraseñaRequestBody(string token, string newPassword) {
            this.token = token;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambioContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambioContraseñaResponse", Namespace="http://sufacturacion.com/", Order=0)]
        public Timbrado.Autenticacion.CambioContraseñaResponseBody Body;
        
        public CambioContraseñaResponse() {
        }
        
        public CambioContraseñaResponse(Timbrado.Autenticacion.CambioContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CambioContraseñaResponseBody {
        
        public CambioContraseñaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAutenticacionSoapChannel : Timbrado.Autenticacion.wsAutenticacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAutenticacionSoapClient : System.ServiceModel.ClientBase<Timbrado.Autenticacion.wsAutenticacionSoap>, Timbrado.Autenticacion.wsAutenticacionSoap {
        
        public wsAutenticacionSoapClient() {
        }
        
        public wsAutenticacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAutenticacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Timbrado.Autenticacion.AutenticarBasicoResponse Timbrado.Autenticacion.wsAutenticacionSoap.AutenticarBasico(Timbrado.Autenticacion.AutenticarBasicoRequest request) {
            return base.Channel.AutenticarBasico(request);
        }
        
        public string AutenticarBasico(string usuario, string password) {
            Timbrado.Autenticacion.AutenticarBasicoRequest inValue = new Timbrado.Autenticacion.AutenticarBasicoRequest();
            inValue.Body = new Timbrado.Autenticacion.AutenticarBasicoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            Timbrado.Autenticacion.AutenticarBasicoResponse retVal = ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).AutenticarBasico(inValue);
            return retVal.Body.AutenticarBasicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoResponse> Timbrado.Autenticacion.wsAutenticacionSoap.AutenticarBasicoAsync(Timbrado.Autenticacion.AutenticarBasicoRequest request) {
            return base.Channel.AutenticarBasicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoResponse> AutenticarBasicoAsync(string usuario, string password) {
            Timbrado.Autenticacion.AutenticarBasicoRequest inValue = new Timbrado.Autenticacion.AutenticarBasicoRequest();
            inValue.Body = new Timbrado.Autenticacion.AutenticarBasicoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).AutenticarBasicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse Timbrado.Autenticacion.wsAutenticacionSoap.AutenticarBasicoBatchProcess(Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest request) {
            return base.Channel.AutenticarBasicoBatchProcess(request);
        }
        
        public string AutenticarBasicoBatchProcess(string usuario, string password) {
            Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest inValue = new Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest();
            inValue.Body = new Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse retVal = ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).AutenticarBasicoBatchProcess(inValue);
            return retVal.Body.AutenticarBasicoBatchProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse> Timbrado.Autenticacion.wsAutenticacionSoap.AutenticarBasicoBatchProcessAsync(Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest request) {
            return base.Channel.AutenticarBasicoBatchProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<Timbrado.Autenticacion.AutenticarBasicoBatchProcessResponse> AutenticarBasicoBatchProcessAsync(string usuario, string password) {
            Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest inValue = new Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequest();
            inValue.Body = new Timbrado.Autenticacion.AutenticarBasicoBatchProcessRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).AutenticarBasicoBatchProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Timbrado.Autenticacion.TokenCambioContraseñaResponse Timbrado.Autenticacion.wsAutenticacionSoap.TokenCambioContraseña(Timbrado.Autenticacion.TokenCambioContraseñaRequest request) {
            return base.Channel.TokenCambioContraseña(request);
        }
        
        public string TokenCambioContraseña(string apiKey, string email) {
            Timbrado.Autenticacion.TokenCambioContraseñaRequest inValue = new Timbrado.Autenticacion.TokenCambioContraseñaRequest();
            inValue.Body = new Timbrado.Autenticacion.TokenCambioContraseñaRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.email = email;
            Timbrado.Autenticacion.TokenCambioContraseñaResponse retVal = ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).TokenCambioContraseña(inValue);
            return retVal.Body.TokenCambioContraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.TokenCambioContraseñaResponse> Timbrado.Autenticacion.wsAutenticacionSoap.TokenCambioContraseñaAsync(Timbrado.Autenticacion.TokenCambioContraseñaRequest request) {
            return base.Channel.TokenCambioContraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Timbrado.Autenticacion.TokenCambioContraseñaResponse> TokenCambioContraseñaAsync(string apiKey, string email) {
            Timbrado.Autenticacion.TokenCambioContraseñaRequest inValue = new Timbrado.Autenticacion.TokenCambioContraseñaRequest();
            inValue.Body = new Timbrado.Autenticacion.TokenCambioContraseñaRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.email = email;
            return ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).TokenCambioContraseñaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Timbrado.Autenticacion.CambioContraseñaResponse Timbrado.Autenticacion.wsAutenticacionSoap.CambioContraseña(Timbrado.Autenticacion.CambioContraseñaRequest request) {
            return base.Channel.CambioContraseña(request);
        }
        
        public void CambioContraseña(string token, string newPassword) {
            Timbrado.Autenticacion.CambioContraseñaRequest inValue = new Timbrado.Autenticacion.CambioContraseñaRequest();
            inValue.Body = new Timbrado.Autenticacion.CambioContraseñaRequestBody();
            inValue.Body.token = token;
            inValue.Body.newPassword = newPassword;
            Timbrado.Autenticacion.CambioContraseñaResponse retVal = ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).CambioContraseña(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Timbrado.Autenticacion.CambioContraseñaResponse> Timbrado.Autenticacion.wsAutenticacionSoap.CambioContraseñaAsync(Timbrado.Autenticacion.CambioContraseñaRequest request) {
            return base.Channel.CambioContraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Timbrado.Autenticacion.CambioContraseñaResponse> CambioContraseñaAsync(string token, string newPassword) {
            Timbrado.Autenticacion.CambioContraseñaRequest inValue = new Timbrado.Autenticacion.CambioContraseñaRequest();
            inValue.Body = new Timbrado.Autenticacion.CambioContraseñaRequestBody();
            inValue.Body.token = token;
            inValue.Body.newPassword = newPassword;
            return ((Timbrado.Autenticacion.wsAutenticacionSoap)(this)).CambioContraseñaAsync(inValue);
        }
    }
}
